[build-system]
requires = ["flit_core >=3.2,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "compuglobal"
authors = [
    {name = "MitchellAW"},
]
readme = "README.rst"
license = "MIT"
requires-python = ">=3.13"
dynamic = ["version", "description"]
dependencies = [
    "aiohttp>=3.13.0", "pydantic>=2.13.0"
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers"
]
keywords = [
    "The Simpsons", "Futurama", "Rick and Morty", "West Wing", "Frinkiac", "Morbotron", "Master of all Science", "Capital Beat", "API", "API Wrapper", "CompuGlobal", "CompuGlobalHyperMegaNet", "CGHMC"
]

[dependency-groups]
dev = [
    "ruff>=0.15.13",
]
docs = [
    "enum-tools[sphinx]>=0.13.0",
    "sphinx<9.0",
    "sphinx-rtd-theme>=3.1.0",
    "sphinxcontrib-trio>=1.2.0",
]

[project.urls]
Documentation = "https://compuglobal.readthedocs.io/en/latest/"
Source = "https://github.com/MitchellAW/CompuGlobal"

[tool.uv]
package = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N", "B", "S", "PL", "UP", "ASYNC", "DOC"]
